import type { MetadataRoute } from "next";

/**
 * Web App Manifest (served as `/manifest.webmanifest`).
 *
 * Icon URLs reference the two PNGs generated by `src/app/icon.tsx` at build
 * time. Keep the `id` fields in that file in sync with the paths here.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "BAI Health",
    short_name: "BAI",
    description:
      "Body Awareness Index — BMI + BRI framed around your own journey, stored locally on your device.",
    start_url: "/",
    scope: "/",
    display: "standalone",
    orientation: "portrait",
    background_color: "#fafafa",
    theme_color: "#18181b",
    categories: ["health", "lifestyle", "fitness"],
    icons: [
      {
        src: "/icon/192",
        sizes: "192x192",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icon/512",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icon/512-maskable",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
